import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { generateAttributePrompts } from "../../../src/config/attributes.ts";

export class AttributePromptService {
  static async generateAttributePrompts(userId: string, companyName: string, industry: string) {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    try {
      // Generate the attribute prompts
      const prompts = generateAttributePrompts(companyName, industry);

      // Insert prompts directly into confirmed_prompts table
      const { error: insertError } = await supabase
        .from('confirmed_prompts')
        .insert(
          prompts.map(prompt => ({
            user_id: userId,
            onboarding_id: null, // Generated by service, not onboarding
            prompt_text: prompt.prompt,
            prompt_type: prompt.type,
            attribute_id: prompt.attributeId,
            is_active: true
          }))
        );

      if (insertError) {
        console.error('Error inserting attribute prompts:', insertError);
        throw insertError;
      }

      console.log(`Generated ${prompts.length} attribute prompts for user ${userId}`);
      return prompts;

    } catch (error) {
      console.error('Error in generateAttributePrompts:', error);
      throw error;
    }
  }

  static async hasAttributePrompts(userId: string): Promise<boolean> {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    try {
      const { data, error } = await supabase
        .from('confirmed_prompts')
        .select('id')
        .eq('user_id', userId)
        .not('attribute_id', 'is', null)
        .limit(1);

      if (error) throw error;
      return data && data.length > 0;

    } catch (error) {
      console.error('Error checking attribute prompts:', error);
      return false;
    }
  }

  static async getAttributePrompts(userId: string) {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    try {
      const { data, error } = await supabase
        .from('confirmed_prompts')
        .select('*')
        .eq('user_id', userId)
        .not('attribute_id', 'is', null)
        .order('created_at', { ascending: true });

      if (error) throw error;
      return data || [];

    } catch (error) {
      console.error('Error fetching attribute prompts:', error);
      return [];
    }
  }
}
