/**
 * Map country codes to flag emojis
 * @param countryCode - ISO country code (e.g., 'US', 'GB', 'GLOBAL')
 * @returns Flag emoji string or empty string if country is GLOBAL or not found
 */
export function getCountryFlag(countryCode: string | null | undefined): string {
  if (!countryCode || countryCode === 'GLOBAL') {
    return '';
  }

  const countryFlags: Record<string, string> = {
    'AX': '🇦🇽',
    'AD': '🇦🇩',
    'AI': '🇦🇮',
    'AQ': '🇦🇶',
    'AG': '🇦🇬',
    'AR': '🇦🇷',
    'AW': '🇦🇼',
    'AU': '🇦🇺',
    'AT': '🇦🇹',
    'BS': '🇧🇸',
    'BB': '🇧🇧',
    'BE': '🇧🇪',
    'BM': '🇧🇲',
    'BV': '🇧🇻',
    'BR': '🇧🇷',
    'IO': '🇮🇴',
    'VG': '🇻🇬',
    'BG': '🇧🇬',
    'CA': '🇨🇦',
    'BQ': '🇧🇶',
    'KY': '🇰🇾',
    'CL': '🇨🇱',
    'CO': '🇨🇴',
    'HR': '🇭🇷',
    'CU': '🇨🇺',
    'CW': '🇨🇼',
    'CY': '🇨🇾',
    'CZ': '🇨🇿',
    'DK': '🇩🇰',
    'DM': '🇩🇲',
    'DO': '🇩🇴',
    'EE': '🇪🇪',
    'FK': '🇫🇰',
    'FO': '🇫🇴',
    'FI': '🇫🇮',
    'FR': '🇫🇷',
    'GF': '🇬🇫',
    'PF': '🇵🇫',
    'DE': '🇩🇪',
    'GI': '🇬🇮',
    'GR': '🇬🇷',
    'GL': '🇬🇱',
    'GD': '🇬🇩',
    'GP': '🇬🇵',
    'HT': '🇭🇹',
    'HM': '🇭🇲',
    'HU': '🇭🇺',
    'IS': '🇮🇸',
    'IN': '🇮🇳',
    'ID': '🇮🇩',
    'IE': '🇮🇪',
    'IT': '🇮🇹',
    'JM': '🇯🇲',
    'JP': '🇯🇵',
    'LV': '🇱🇻',
    'LI': '🇱🇮',
    'LT': '🇱🇹',
    'LU': '🇱🇺',
    'MY': '🇲🇾',
    'MT': '🇲🇹',
    'MQ': '🇲🇶',
    'YT': '🇾🇹',
    'MX': '🇲🇽',
    'MC': '🇲🇨',
    'MS': '🇲🇸',
    'NL': '🇳🇱',
    'NC': '🇳🇨',
    'NZ': '🇳🇿',
    'NO': '🇳🇴',
    'PS': '🇵🇸',
    'PE': '🇵🇪',
    'PH': '🇵🇭',
    'PL': '🇵🇱',
    'PT': '🇵🇹',
    'PR': '🇵🇷',
    'RE': '🇷🇪',
    'RO': '🇷🇴',
    'BL': '🇧🇱',
    'KN': '🇰🇳',
    'LC': '🇱🇨',
    'MF': '🇲🇫',
    'PM': '🇵🇲',
    'VC': '🇻🇨',
    'SM': '🇸🇲',
    'SA': '🇸🇦',
    'SG': '🇸🇬',
    'SX': '🇸🇽',
    'SK': '🇸🇰',
    'SI': '🇸🇮',
    'ZA': '🇿🇦',
    'GS': '🇬🇸',
    'KR': '🇰🇷',
    'ES': '🇪🇸',
    'SJ': '🇸🇯',
    'SE': '🇸🇪',
    'CH': '🇨🇭',
    'TH': '🇹🇭',
    'TT': '🇹🇹',
    'TR': '🇹🇷',
    'TC': '🇹🇨',
    'AE': '🇦🇪',
    'GB': '🇬🇧',
    'US': '🇺🇸',
    // US sub-national locations (ISO 3166-2) share the US flag.
    'US-MI': '🇺🇸',
    'US-KY': '🇺🇸',
    'VA': '🇻🇦',
    'VE': '🇻🇪',
    'VN': '🇻🇳',
    'WF': '🇼🇫',
  };

  return countryFlags[countryCode.toUpperCase()] || '';
}


