-- Recovered verbatim from supabase_migrations.schema_migrations.
-- Applied to production as migration version 20260312125122; this file was
-- back-filled afterwards and therefore post-dates the deployment.


-- Insert canonical name mappings. ON CONFLICT DO NOTHING skips any already existing.
INSERT INTO company_canonical_names (variant_name, canonical_name) VALUES
  ('3m company',                                  '3M'),
  ('abbvie deutschland',                          'Abbvie'),
  ('aditya birla fashion and retail limited',     'Aditya Birla Fashion and Retail'),
  ('aeg europe',                                  'Aeg'),
  ('aeg worldwide',                               'Aeg'),
  ('aesop latam',                                 'Aesop'),
  ('aia life insurance company',                  'Aia Life Insurance'),
  ('aia life insurance company limited',          'Aia Life Insurance'),
  ('air india limited',                           'Air India'),
  ('air france – klm',                            'Air France-klm'),
  ('air france–klm',                              'Air France-klm'),
  ('airbus helicopters deutschland',              'Airbus Helicopters'),
  ('ajanta pharma limited',                       'Ajanta Pharma'),
  ('allegiant travel company',                    'Allegiant Travel'),
  ('amazon deutschland',                          'Amazon'),
  ('amazon france logistics',                     'Amazon Logistics'),
  ('amazon france logistique',                    'Amazon Logistics'),
  ('american fidelity assurance company',         'American Fidelity Assurance'),
  ('angel one limited',                           'Angel One'),
  ('aragen life sciences limited',                'Aragen Life Sciences'),
  ('aramark deutschland',                         'Aramark'),
  ('armor-lux',                                   'Armor Lux'),
  ('astronautics corporation of america',         'Astronautics Corp of America'),
  ('axa deutschland',                             'Axa'),
  ('axis asset management company',               'Axis Asset Management'),
  ('axis asset management company limited',       'Axis Asset Management'),
  ('axis max life insurance limited',             'Axis Max Life Insurance'),
  ('aye finance limited',                         'Aye Finance'),
  ('bain & company',                              'Bain'),
  ('bajaj consumer care limited',                 'Bajaj Consumer Care'),
  ('bajaj finance limited',                       'Bajaj Finance'),
  ('bentley motors limited',                      'Bentley Motors'),
  ('bharat electronics limited',                  'Bharat Electronics'),
  ('biocon limited',                              'Biocon'),
  ('biossance latam',                             'Biossance'),
  ('birmingham airport limited',                  'Birmingham Airport'),
  ('bnp paribas deutschland',                     'BNP Paribas'),
  ('boehringer ingelheim – animal health',        'Boehringer Ingelheim Animal Health'),
  ('bridgestone americas',                        'Bridgestone'),
  ('brinton pharmaceuticals limited',             'Brinton Pharmaceuticals'),
  ('bristol-myers squibb',                        'Bristol Myers Squibb'),
  ('burger king deutschland',                     'Burger King'),
  ('byd company limited',                         'Byd'),
  ('center parcs deutschland',                    'Center Parcs Europe'),
  ('central garden & pet company',                'Central Garden & Pet'),
  ('chiesi limited',                              'Chiesi'),
  ('cipla limited',                               'Cipla'),
  ('coca-cola company',                           'Coca-cola'),
  ('the coca cola company',                       'Coca-cola'),
  ('the coca-cola company',                       'Coca-cola'),
  ('columbia sportswear company',                 'Columbia Sportswear'),
  ('china cosco shipping',                        'Cosco Shipping'),
  ('cox automotive europe',                       'Cox Automotive'),
  ('cspc pharmaceutical group limited',           'Cspc Pharmaceutical'),
  ('dabur india limited',                         'Dabur'),
  ('danone north america',                        'Danone'),
  ('decathlon deutschland',                       'Decathlon'),
  ('deloitte llp',                                'Deloitte'),
  ('dji-innovations',                             'Dji Innovations'),
  ('domino''s pizza deutschland',                 'Domino''s Pizza'),
  ('dpd deutschland',                             'Dpd'),
  ('dynatrace limited',                           'Dynatrace'),
  ('ee limited',                                  'Ee'),
  ('elanco deutschland',                          'Elanco'),
  ('elbit america',                               'Elbit'),
  ('eli lilly & company',                         'Eli Lilly'),
  ('lilly',                                       'Eli Lilly'),
  ('lilly deutschland',                           'Eli Lilly'),
  ('esprit europe',                               'Esprit'),
  ('faw–volkswagen',                              'Faw-volkswagen'),
  ('ferrero deutschland',                         'Ferrero'),
  ('generali deutschland',                        'Generali'),
  ('godrej consumer products limited',            'Godrej Consumer Products'),
  ('gxo logistics uk limited',                    'Gxo Logistics'),
  ('havells india',                               'Havells'),
  ('hdfc asset management company',               'Hdfc Asset Management'),
  ('hdfc asset management company limited',       'Hdfc Asset Management'),
  ('hero fincorp limited',                        'Hero Fincorp'),
  ('hershey company',                             'Hershey'),
  ('the hershey company',                         'Hershey'),
  ('hewlett-packard',                             'Hewlett Packard'),
  ('hilton worldwide',                            'Hilton'),
  ('hindustan unilever limited',                  'Hindustan Unilever'),
  ('honda north america',                         'Honda'),
  ('iifl finance limited',                        'Iifl Finance'),
  ('iit-delhi',                                   'Iit Delhi'),
  ('ikea deutschland',                            'Ikea'),
  ('immediate media company',                     'Immediate Media'),
  ('ing deutschland',                             'Ing'),
  ('itc limited',                                 'Itc'),
  ('kaya limited',                                'Kaya'),
  ('kellogg company',                             'Kellogg'),
  ('kfc deutschland',                             'KFC'),
  ('kia uk',                                      'Kia'),
  ('kia uk limited',                              'Kia'),
  ('kotak securities limited',                    'Kotak Securities'),
  ('kpmg llp',                                    'KPMG'),
  ('kraft-heinz',                                 'Kraft Heinz'),
  ('lg electronics north america',                'Lg Electronics'),
  ('li-ning',                                     'Li Ning'),
  ('lidl deutschland',                            'Lidl'),
  ('liebherr-aerospace',                          'Liebherr Aerospace'),
  ('china life insurance company',                'China Life Insurance'),
  ('lupin limited',                               'Lupin'),
  ('lvmh deutschland',                            'LVMH'),
  ('mahindra holidays & resorts india limited',   'Mahindra Holidays & Resorts'),
  ('mahindra logistics limited',                  'Mahindra Logistics'),
  ('marico limited',                              'Marico'),
  ('marsh & mclennan',                            'Marsh Mclennan'),
  ('marsh & mclennan agency',                     'Marsh Mclennan Agency'),
  ('maruti suzuki india limited',                 'Maruti Suzuki'),
  ('max healthcare institute limited',            'Max Healthcare Institute'),
  ('mcdonald''s deutschland',                     'McDonald''s'),
  ('mcdonald''s brasil',                          'McDonald''s'),
  ('mcdonald''s india',                           'McDonald''s'),
  ('mckinsey & company',                          'Mckinsey'),
  ('china medical system holdings limited',       'China Medical System'),
  ('mgm china holdings limited',                  'Mgm China'),
  ('michelin north america',                      'Michelin'),
  ('moelis & company',                            'Moelis'),
  ('mott macdonald group limited',                'Mott Macdonald'),
  ('msa safety company',                          'Msa Safety'),
  ('msa safety incorporated',                     'Msa Safety'),
  ('msa - the safety company',                    'Msa Safety'),
  ('muthoot fincorp limited',                     'Muthoot Fincorp'),
  ('national insurance company',                  'National Insurance'),
  ('nationwide mutual insurance company',         'Nationwide Mutual Insurance'),
  ('natura & co',                                 'Natura'),
  ('nestlé deutschland',                          'Nestlé'),
  ('niit limited',                                'Niit'),
  ('nissan north america',                        'Nissan'),
  ('o2 telefónica deutschland',                   'O2 Telefónica'),
  ('oriental insurance company',                  'Oriental Insurance'),
  ('china pacific insurance company',             'China Pacific Insurance'),
  ('palletforce limited',                         'Palletforce'),
  ('panasonic north america',                     'Panasonic'),
  ('patagonia europe',                            'Patagonia'),
  ('pfizer deutschland',                          'Pfizer'),
  ('pierre & vacances – center parcs',            'Pierre & Vacances Center Parcs'),
  ('pierre & vacances–center parcs',              'Pierre & Vacances Center Parcs'),
  ('piramal capital & housing finance limited',   'Piramal Capital & Housing Finance'),
  ('pwc india',                                   'PwC'),
  ('qbe europe',                                  'Qbe'),
  ('raymond limited',                             'Raymond'),
  ('raymond lifestyle limited',                   'Raymond Lifestyle'),
  ('reliance industries limited',                 'Reliance Industries'),
  ('ricardo uk limited',                          'Ricardo'),
  ('roche deutschland',                           'Roche'),
  ('roche diagnostics deutschland',               'Roche Diagnostics'),
  ('rolls-royce deutschland',                     'Rolls-royce'),
  ('rsm us llp',                                  'Rsm'),
  ('rtl deutschland',                             'Rtl'),
  ('saic–gm',                                     'Saic-gm'),
  ('saic-volkswagen',                             'Saic Volkswagen'),
  ('saint-gobain',                                'Saint Gobain'),
  ('saint-gobain north america',                  'Saint Gobain'),
  ('samsung electronics america',                 'Samsung Electronics'),
  ('samsung india electronics',                   'Samsung Electronics'),
  ('samsung sdi america',                         'Samsung Sdi'),
  ('saregama india limited',                      'Saregama'),
  ('sbi funds management limited',                'Sbi Funds Management'),
  ('scandic hotels deutschland',                  'Scandic Hotels'),
  ('sega europe',                                 'Sega'),
  ('shiseido americas',                           'Shiseido'),
  ('sinotrans limited',                           'Sinotrans'),
  ('sky deutschland',                             'Sky'),
  ('sodexo deutschland',                          'Sodexo'),
  ('sonesta international hotels',                'Sonesta Hotels'),
  ('starbucks deutschland',                       'Starbucks'),
  ('stellantis north america',                    'Stellantis'),
  ('subway deutschland',                          'Subway'),
  ('sunexpress deutschland',                      'Sunexpress'),
  ('t-mobile us',                                 'T-mobile'),
  ('tal apparel limited',                         'Tal Apparel'),
  ('tata capital limited',                        'Tata Capital'),
  ('tata power company',                          'Tata Power'),
  ('tata steel europe',                           'Tata Steel'),
  ('tcl north america',                           'Tcl'),
  ('tcns clothing company',                       'Tcns Clothing'),
  ('telefonica brasil',                           'Telefonica'),
  ('telefónica deutschland',                      'Telefónica'),
  ('telekom deutschland',                         'Telekom'),
  ('tencent holdings limited',                    'Tencent'),
  ('the body shop latam',                         'The Body Shop'),
  ('thomas cook india',                           'Thomas Cook'),
  ('titan company',                               'Titan'),
  ('titan company limited',                       'Titan'),
  ('toyota europe',                               'Toyota'),
  ('toyota north america',                        'Toyota'),
  ('toyota motor north america',                  'Toyota Motor Europe'),
  ('tractor supply company',                      'Tractor Supply'),
  ('trent limited',                               'Trent'),
  ('triodos bank deutschland',                    'Triodos Bank'),
  ('tui deutschland',                             'Tui'),
  ('tui fly deutschland',                         'Tui Fly'),
  ('tuifly deutschland',                          'Tuifly'),
  ('tvs motor company',                           'Tvs Motor'),
  ('unilever deutschland',                        'Unilever'),
  ('unipart logistics limited',                   'Unipart Logistics'),
  ('virgin america',                              'Virgin'),
  ('visa europe',                                 'Visa'),
  ('vodafone idea limited',                       'Vodafone Idea'),
  ('volksbanken & raiffeisenbanken',              'Volksbanken Raiffeisenbanken'),
  ('volvo group north america',                   'Volvo'),
  ('walt disney company',                         'Walt Disney'),
  ('west bend insurance company',                 'West Bend Insurance'),
  ('wincanton limited',                           'Wincanton'),
  ('wipro limited',                               'Wipro'),
  ('xpo logistics europe',                        'Xpo Logistics'),
  ('yum china',                                   'Yum'),
  ('yum china holdings limited',                  'Yum'),
  ('yum! brands',                                 'Yum'),
  ('zee entertainment enterprises limited',       'Zee Entertainment Enterprises'),
  ('zurich north america',                        'Zurich')
ON CONFLICT (variant_name) DO UPDATE SET canonical_name = EXCLUDED.canonical_name;

