-- Recovered verbatim from supabase_migrations.schema_migrations.
-- Applied to production as migration version 20260520131418; this file was
-- back-filled afterwards and therefore post-dates the deployment.

BEGIN;
CREATE EXTENSION IF NOT EXISTS unaccent;
ALTER TABLE public.company_canonical_names ADD COLUMN IF NOT EXISTS brand_key text;
UPDATE public.company_canonical_names SET brand_key = lower(public.unaccent(canonical_name)) WHERE brand_key IS NULL OR brand_key = '';

CREATE TEMP TABLE _classifications (canonical_name text NOT NULL, variant_name text NOT NULL, new_variant_type text NOT NULL, brand_key text NOT NULL, reason text) ON COMMIT DROP;

INSERT INTO _classifications (canonical_name, variant_name, new_variant_type, brand_key, reason) VALUES
  ('Nestlé','purina','subsidiary','purina','Purina collision'),
  ('Nestlé','nestle purina','subsidiary','purina','Purina collision'),
  ('Nestlé','nestlé purina','subsidiary','purina','Purina collision'),
  ('Nestlé','nestle purina petcare','subsidiary','purina','Purina collision'),
  ('Nestlé','nestlé purina petcare','subsidiary','purina','Purina collision'),
  ('Nestlé','nestlé health science','subsidiary','nestle health science',''),
  ('Nestlé','nestle','alias','nestle',''),
  ('Nestlé','nestlé','alias','nestle',''),
  ('Nestlé','nestlé group','alias','nestle',''),
  ('Nestlé','nestlé sa','parent','nestle',''),
  ('Nestlé','nestlé dairy','alias','nestle',''),
  ('Nestlé','purina betterwithpets','alias','purina',''),
  ('Nestlé','purina one','alias','purina',''),
  ('Nestlé','nestlé brasil','geo','nestle',''),
  ('Nestlé','nestlé brasil ltda','geo','nestle',''),
  ('Nestlé','nestlé brazil','geo','nestle',''),
  ('Nestlé','nestlé china','geo','nestle',''),
  ('Nestlé','nestlé deutschland','geo','nestle',''),
  ('Nestlé','nestlé france','geo','nestle',''),
  ('Nestlé','nestle india','geo','nestle',''),
  ('Nestlé','nestlé india','geo','nestle',''),
  ('Nestlé','nestlé uk','geo','nestle',''),
  ('Nestlé','nestlé usa','geo','nestle',''),
  ('Nestlé','nestlé waters canada','geo','nestle',''),
  ('Nestlé','nestlé health science france','geo','nestle health science',''),
  ('Nestlé','nestlé purina brasil','geo','purina',''),
  ('Nestlé','nestlé purina brazil','geo','purina',''),
  ('Nestlé','nestlé purina china','geo','purina',''),
  ('Nestlé','nestlé purina germany','geo','purina',''),
  ('Nestlé','nestlé purina petcare china','geo','purina',''),
  ('Nestlé','nestlé purina petcare deutschland gmbh','geo','purina',''),
  ('Nestlé','nestlé purina petcare france','geo','purina',''),
  ('Nestlé','nestlé purina petcare france sas','geo','purina',''),
  ('Nestlé','nestlé purina petcare germany','geo','purina',''),
  ('Nestlé','nestlé purina petcare india','geo','purina',''),
  ('Nestlé','nestlé purina petcare uk','geo','purina',''),
  ('Nestlé','nestlé purina uk','geo','purina',''),
  ('Nestlé','purina france','geo','purina',''),
  ('Nestlé','purina uk','geo','purina',''),
  ('Amazon','aws','subsidiary','aws',''),
  ('Amazon','amazon web services','subsidiary','aws',''),
  ('Amazon','amazon web services (aws)','subsidiary','aws',''),
  ('Amazon','amazon games','subsidiary','amazon games',''),
  ('Amazon','amazon kuiper','subsidiary','kuiper',''),
  ('Amazon','amazon lab126','subsidiary','lab126',''),
  ('Amazon','amazon mgm studios','subsidiary','mgm studios',''),
  ('Amazon','amazon music','subsidiary','amazon music',''),
  ('Amazon','amazon prime video','subsidiary','prime video',''),
  ('Amazon','prime video','subsidiary','prime video',''),
  ('Amazon','amazon studios','subsidiary','amazon studios',''),
  ('Amazon','twitch','subsidiary','twitch',''),
  ('Amazon','amazon','alias','amazon',''),
  ('Amazon','amazon aws','alias','aws',''),
  ('Amazon','amazon web services (aws) (cloud data platform)','alias','aws',''),
  ('Amazon','aws ai','alias','aws',''),
  ('Amazon','aws proserve','alias','aws',''),
  ('Amazon','amazon logistics','alias','amazon',''),
  ('Amazon','amazon logistik','alias','amazon',''),
  ('Amazon','amazon payments','alias','amazon',''),
  ('Amazon','amazon (retail division)','alias','amazon',''),
  ('Amazon','amazon transportation services','alias','amazon',''),
  ('Amazon','amazon forever','alias','amazon',''),
  ('Amazon','amazon brasil','geo','amazon',''),
  ('Amazon','amazon brazil','geo','amazon',''),
  ('Amazon','amazon deutschland','geo','amazon',''),
  ('Amazon','amazon france','geo','amazon',''),
  ('Amazon','amazon france logistics','geo','amazon',''),
  ('Amazon','amazon france logistique','geo','amazon',''),
  ('Amazon','amazon germany','geo','amazon',''),
  ('Amazon','amazon india','geo','amazon',''),
  ('Amazon','amazon logistics germany','geo','amazon',''),
  ('Amazon','amazon logistics (uk)','geo','amazon',''),
  ('Amazon','amazon logistics uk','geo','amazon',''),
  ('Amazon','amazon pay india','geo','amazon',''),
  ('Amazon','amazon prime video india','geo','prime video',''),
  ('Amazon','amazon transportation services (ats india)','geo','amazon',''),
  ('Amazon','amazon transportation services (india)','geo','amazon',''),
  ('Amazon','amazon transportation services india','geo','amazon',''),
  ('Amazon','amazon uk','geo','amazon',''),
  ('Roche','genentech','subsidiary','genentech',''),
  ('Roche','genentech/roche','subsidiary','genentech',''),
  ('Roche','genentech (roche group)','subsidiary','genentech',''),
  ('Roche','roche/genentech','subsidiary','genentech',''),
  ('Roche','roche diagnostics','subsidiary','roche diagnostics',''),
  ('Roche','roche pharma','subsidiary','roche pharma',''),
  ('Roche','roche diagnostics gmbh','alias','roche diagnostics',''),
  ('Roche','roche','alias','roche',''),
  ('Roche','roche group','alias','roche',''),
  ('Roche','roche holding ag','parent','roche',''),
  ('Roche','genentech india','geo','genentech',''),
  ('Roche','roche brasil','geo','roche',''),
  ('Roche','roche brazil','geo','roche',''),
  ('Roche','roche china','geo','roche',''),
  ('Roche','roche deutschland','geo','roche',''),
  ('Roche','roche diabetes care france','geo','roche',''),
  ('Roche','roche diagnostics deutschland','geo','roche diagnostics',''),
  ('Roche','roche diagnostics germany','geo','roche diagnostics',''),
  ('Roche','roche diagnostics india','geo','roche diagnostics',''),
  ('Roche','roche france','geo','roche',''),
  ('Roche','roche germany','geo','roche',''),
  ('Roche','roche india','geo','roche',''),
  ('Roche','roche information solutions india','geo','roche',''),
  ('Roche','roche pharma india','geo','roche pharma',''),
  ('Roche','roche uk','geo','roche',''),
  ('PepsiCo','aquafina','subsidiary','aquafina',''),
  ('PepsiCo','cheetos','subsidiary','cheetos',''),
  ('PepsiCo','doritos','subsidiary','doritos',''),
  ('PepsiCo','frito lay','subsidiary','frito-lay',''),
  ('PepsiCo','frito-lay','subsidiary','frito-lay',''),
  ('PepsiCo','gatorade','subsidiary','gatorade',''),
  ('PepsiCo','lay''s','subsidiary','lays',''),
  ('PepsiCo','lays','subsidiary','lays',''),
  ('PepsiCo','mountain dew','subsidiary','mountain dew',''),
  ('PepsiCo','naked juice','subsidiary','naked juice',''),
  ('PepsiCo','pepsi','subsidiary','pepsi',''),
  ('PepsiCo','propel','subsidiary','propel',''),
  ('PepsiCo','quaker','subsidiary','quaker',''),
  ('PepsiCo','quaker oats','subsidiary','quaker',''),
  ('PepsiCo','rockstar energy','subsidiary','rockstar energy',''),
  ('PepsiCo','sabra','subsidiary','sabra',''),
  ('PepsiCo','sodastream','subsidiary','sodastream',''),
  ('PepsiCo','tropicana','subsidiary','tropicana',''),
  ('PepsiCo','pepsico','alias','pepsico',''),
  ('PepsiCo','pepsico inc','alias','pepsico',''),
  ('PepsiCo','pepsico brasil','geo','pepsico',''),
  ('PepsiCo','pepsico china','geo','pepsico',''),
  ('PepsiCo','pepsico india','geo','pepsico',''),
  ('PepsiCo','pepsico uk','geo','pepsico',''),
  ('Google','deepmind','subsidiary','deepmind',''),
  ('Google','google deepmind','subsidiary','deepmind',''),
  ('Google','fitbit','subsidiary','fitbit',''),
  ('Google','google cloud','subsidiary','google cloud',''),
  ('Google','google cloud platform','subsidiary','google cloud',''),
  ('Google','google nest','subsidiary','google nest',''),
  ('Google','waymo','subsidiary','waymo',''),
  ('Google','waymo (alphabet)','subsidiary','waymo',''),
  ('Google','youtube','subsidiary','youtube',''),
  ('Google','alphabet','parent','alphabet',''),
  ('Google','alphabet inc','parent','alphabet',''),
  ('Google','alphabet inc.','parent','alphabet',''),
  ('Google','google','alias','google',''),
  ('Google','google ai','alias','google',''),
  ('Google','google (alphabet)','alias','google',''),
  ('Google','google brain','alias','google',''),
  ('Google','google cloud platform (gcp)','alias','google cloud',''),
  ('Google','google cloud security','alias','google cloud',''),
  ('Google','google cloud vertex ai','alias','google cloud',''),
  ('Google','google deepmind paris','alias','deepmind',''),
  ('Google','google fiber','alias','google',''),
  ('Google','google flights','alias','google',''),
  ('Google','google pay','alias','google',''),
  ('Google','google play games','alias','google',''),
  ('Google','google research','alias','google',''),
  ('Google','google brasil','geo','google',''),
  ('Google','google brazil','geo','google',''),
  ('Google','google cloud brazil','geo','google cloud',''),
  ('Google','google france','geo','google',''),
  ('Google','google germany','geo','google',''),
  ('Google','google india','geo','google',''),
  ('Google','google research india','geo','google',''),
  ('Google','google spain','geo','google',''),
  ('Google','google uk','geo','google',''),
  ('Google','youtube india','geo','youtube',''),
  ('Disney','the walt disney company','parent','the walt disney company',''),
  ('Disney','walt disney company','parent','the walt disney company',''),
  ('Disney','walt disney','alias','disney',''),
  ('Disney','disney','alias','disney',''),
  ('Disney','adventures by disney','alias','disney',''),
  ('Disney','disney cruise line','alias','disney',''),
  ('Disney','disney cruise line & parks','alias','disney',''),
  ('Disney','disney impact','alias','disney',''),
  ('Disney','disneyland paris','alias','disney',''),
  ('Disney','disney parks','alias','disney',''),
  ('Disney','disney parks and resorts','alias','disney',''),
  ('Disney','disney star','alias','disney',''),
  ('Disney','walt disney parks','alias','disney',''),
  ('Disney','walt disney world resort','alias','disney',''),
  ('Disney','disney china','geo','disney',''),
  ('Disney','disney france','geo','disney',''),
  ('Disney','disney india','geo','disney',''),
  ('Disney','disney star (the walt disney company india)','geo','disney',''),
  ('Disney','the walt disney company brazil','geo','disney',''),
  ('Meta','meta platforms','parent','meta',''),
  ('Meta','meta platforms inc','parent','meta',''),
  ('Meta','meta platforms inc.','parent','meta',''),
  ('Meta','meta','alias','meta',''),
  ('Meta','meta ai','alias','meta',''),
  ('Meta','meta it','alias','meta',''),
  ('Meta','facebook','subsidiary','facebook',''),
  ('Meta','facebook ai research','alias','facebook',''),
  ('TJX','homegoods','subsidiary','homegoods',''),
  ('TJX','homesense','subsidiary','homesense',''),
  ('TJX','marshalls','subsidiary','marshalls',''),
  ('TJX','tj maxx','subsidiary','tj maxx',''),
  ('TJX','tk maxx','subsidiary','tk maxx',''),
  ('Coca-Cola','costa coffee','subsidiary','costa coffee',''),
  ('Coca-Cola','fanta','subsidiary','fanta',''),
  ('Coca-Cola','minute maid','subsidiary','minute maid',''),
  ('Coca-Cola','sprite','subsidiary','sprite',''),
  ('Coca-Cola','coca-cola company','parent','the coca-cola company',''),
  ('Coca-Cola','the coca cola company','parent','the coca-cola company',''),
  ('Coca-Cola','the coca-cola company','parent','the coca-cola company',''),
  ('Coca-Cola','coca-cola','alias','coca-cola',''),
  ('Coca-Cola','coca-cola andina','alias','coca-cola',''),
  ('Coca-Cola','coca-cola europacific partners','alias','coca-cola',''),
  ('Coca-Cola','coca-cola european partners','geo','coca-cola',''),
  ('Coca-Cola','coca-cola femsa','alias','coca-cola',''),
  ('Coca-Cola','hindustan coca-cola beverages','alias','coca-cola',''),
  ('Coca-Cola','swire coca-cola','alias','coca-cola',''),
  ('Coca-Cola','coca-cola brasil','geo','coca-cola',''),
  ('Coca-Cola','coca-cola brazil','geo','coca-cola',''),
  ('Coca-Cola','coca-cola china','geo','coca-cola',''),
  ('Coca-Cola','coca-cola femsa brazil','geo','coca-cola',''),
  ('Coca-Cola','coca-cola india','geo','coca-cola',''),
  ('Coca-Cola','coca-cola uk','geo','coca-cola',''),
  ('Sony','playstation','subsidiary','playstation',''),
  ('Sony','sony interactive entertainment','subsidiary','sony interactive entertainment',''),
  ('Sony','sony music','subsidiary','sony music',''),
  ('Sony','sony music entertainment','subsidiary','sony music',''),
  ('Sony','sony pictures','subsidiary','sony pictures',''),
  ('Sony','sony pictures entertainment','subsidiary','sony pictures',''),
  ('Sony','sony','alias','sony',''),
  ('Sony','sony electronics','alias','sony',''),
  ('Sony','sony group','parent','sony group',''),
  ('Sony','sony group corp','parent','sony group',''),
  ('Sony','sony group corporation','parent','sony group',''),
  ('Sony','sony interactive entertainment (playstation)','alias','sony interactive entertainment',''),
  ('Sony','sony interactive entertainment (sie)','alias','sony interactive entertainment',''),
  ('Sony','sony pictures networks','alias','sony pictures',''),
  ('Sony','sony corporation of america','geo','sony',''),
  ('Sony','sony music entertainment brazil','geo','sony music',''),
  ('Sony','sony music germany','geo','sony music',''),
  ('Sony','sony music uk','geo','sony music',''),
  ('Sony','sony pictures entertainment brazil','geo','sony pictures',''),
  ('Sony','sony pictures networks india','geo','sony pictures',''),
  ('Sony','sony pictures networks india private limited','geo','sony pictures',''),
  ('Sony','sony pictures networks india (spni)','geo','sony pictures',''),
  ('Sony','sony uk','geo','sony',''),
  ('Sony','sony uk technology centre','geo','sony',''),
  ('Mars','mars petcare','subsidiary','mars petcare',''),
  ('Mars','mars veterinary health','subsidiary','mars veterinary health',''),
  ('Mars','mars wrigley','subsidiary','wrigley',''),
  ('Mars','wrigley','subsidiary','wrigley',''),
  ('Mars','mars','alias','mars',''),
  ('Mars','mars inc','parent','mars',''),
  ('Mars','mars inc.','parent','mars',''),
  ('Mars','mars incorporated','parent','mars',''),
  ('Mars','mars group','alias','mars',''),
  ('Mars','mars international','alias','mars',''),
  ('Mars','mars petcare inc','alias','mars petcare',''),
  ('Mars','mars petcare inc.','alias','mars petcare',''),
  ('Tata','tata','alias','tata',''),
  ('Tata','tata group','parent','tata',''),
  ('Tata','tata group companies','parent','tata',''),
  ('Tata','tata sons','parent','tata',''),
  ('Tata','tcs','subsidiary','tcs',''),
  ('Tata','tata consultancy services','subsidiary','tcs',''),
  ('Tata','tata chemicals','subsidiary','tata chemicals',''),
  ('Tata','tata communications','subsidiary','tata communications',''),
  ('Tata','tata consumer','subsidiary','tata consumer',''),
  ('Tata','tata consumer products','subsidiary','tata consumer',''),
  ('Tata','tata elxsi','subsidiary','tata elxsi',''),
  ('Tata','tata motors','subsidiary','tata motors',''),
  ('Tata','tata power','subsidiary','tata power',''),
  ('Tata','tata starbucks','subsidiary','tata starbucks',''),
  ('Tata','tata steel','subsidiary','tata steel',''),
  ('Tata','tata technologies','subsidiary','tata technologies',''),
  ('Tata','jaguar land rover','subsidiary','jaguar land rover',''),
  ('Tata','tata consultancy services (tcs)','alias','tcs',''),
  ('Tata','tcs (tata consultancy services)','alias','tcs',''),
  ('Tata','tata communications limited','alias','tata communications',''),
  ('Tata','tata power company','alias','tata power',''),
  ('Tata','tata steel supply chain','alias','tata steel',''),
  ('Tata','jaguar land rover (jlr)','alias','jaguar land rover',''),
  ('Tata','jaguar land rover china','geo','jaguar land rover',''),
  ('Tata','tata consultancy services (tcs) brazil','geo','tcs',''),
  ('Tata','tata starbucks india','geo','tata starbucks',''),
  ('Tata','tata steel europe','geo','tata steel',''),
  ('Tata','tata steel india limited','geo','tata steel',''),
  ('Tata','tata steel uk','geo','tata steel',''),
  ('Tata','tata steel uk (manufacturing & industrial)','geo','tata steel',''),
  ('Reliance','reliance','alias','reliance',''),
  ('Reliance','reliance industries','parent','reliance industries',''),
  ('Reliance','reliance industries limited','parent','reliance industries',''),
  ('Reliance','reliance industries ltd','parent','reliance industries',''),
  ('Reliance','reliance group','alias','reliance',''),
  ('Reliance','jio','subsidiary','jio',''),
  ('Reliance','reliance jio','subsidiary','jio',''),
  ('Reliance','reliance jio infocomm','alias','jio',''),
  ('Reliance','jio platforms','alias','jio',''),
  ('Reliance','jio platforms (reliance jio)','alias','jio',''),
  ('Reliance','reliance jio platforms','alias','jio',''),
  ('Reliance','jio financial services','alias','jio',''),
  ('Reliance','jio studios','alias','jio',''),
  ('Reliance','jio games','alias','jio',''),
  ('Reliance','reliance retail','subsidiary','reliance retail',''),
  ('Reliance','reliance retail limited','alias','reliance retail',''),
  ('Mahindra','mahindra','alias','mahindra',''),
  ('Mahindra','mahindra group','parent','mahindra',''),
  ('Mahindra','mahindra & mahindra','parent','mahindra',''),
  ('Mahindra','tech mahindra','subsidiary','tech mahindra',''),
  ('Aditya Birla','aditya birla group','parent','aditya birla',''),
  ('Aditya Birla','grasim','subsidiary','grasim',''),
  ('Aditya Birla','hindalco','subsidiary','hindalco',''),
  ('Aditya Birla','aditya birla fashion','subsidiary','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion and retail','subsidiary','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion and retail (abfrl)','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion and retail limited','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion and retail ltd','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion and retail ltd.','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion & retail','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion & retail ltd','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion & retail ltd.','alias','aditya birla fashion',''),
  ('Aditya Birla','aditya birla fashion & retail ltd (abfrl)','alias','aditya birla fashion',''),
  ('Deloitte','deloitte digital','subsidiary','deloitte digital',''),
  ('Deloitte','monitor deloitte','subsidiary','monitor deloitte',''),
  ('Deloitte','deloitte monitor','alias','monitor deloitte',''),
  ('Deloitte','doblin (deloitte)','subsidiary','doblin',''),
  ('PwC','strategy&','subsidiary','strategy&',''),
  ('PwC','strategy& (pwc)','subsidiary','strategy&',''),
  ('PwC','strategy& (pwc strategy)','alias','strategy&',''),
  ('PwC','strategy& (pwc strategy arm)','alias','strategy&',''),
  ('PwC','strategy& (pwc) uk','geo','strategy&',''),
  ('PwC','pricewaterhousecoopers','parent','pricewaterhousecoopers',''),
  ('PwC','pricewaterhousecoopers llp','parent','pricewaterhousecoopers',''),
  ('Unilever','hindustan unilever','subsidiary','hindustan unilever',''),
  ('Unilever','hindustan unilever limited','subsidiary','hindustan unilever',''),
  ('Unilever','hindustan unilever (beauty)','alias','hindustan unilever',''),
  ('Unilever','hindustan unilever limited (hul)','alias','hindustan unilever',''),
  ('Unilever','unilever plc','parent','unilever',''),
  ('Microsoft','microsoft corporation','parent','microsoft',''),
  ('Allianz','allianz se','parent','allianz',''),
  ('Allianz','allianz group','parent','allianz',''),
  ('Volkswagen','volkswagen ag','parent','volkswagen',''),
  ('Volkswagen','volkswagen group','parent','volkswagen',''),
  ('Mercedes-Benz','mercedes-benz group','parent','mercedes-benz',''),
  ('Mercedes-Benz','mercedes-benz group ag','parent','mercedes-benz',''),
  ('Mercedes-Benz','mercedes-benz ag','parent','mercedes-benz',''),
  ('Mercedes-Benz','mercedes amg','subsidiary','mercedes-amg',''),
  ('Mercedes-Benz','mercedes-amg','subsidiary','mercedes-amg',''),
  ('Mercedes-Benz','mercedes amg high performance powertrains','alias','mercedes-amg',''),
  ('L''Oréal','l''oréal s.a.','parent','l''oreal',''),
  ('L''Oréal','l''oréal groupe','parent','l''oreal',''),
  ('L''Oréal','l''oréal group','parent','l''oreal',''),
  ('L''Oréal','l''oreal group','parent','l''oreal',''),
  ('L''Oréal','l''oréal paris','subsidiary','l''oreal paris',''),
  ('L''Oréal','l''oréal professionnel','subsidiary','l''oreal professionnel',''),
  ('DHL','deutsche post dhl','parent','deutsche post dhl',''),
  ('DHL','deutsche post dhl group','parent','deutsche post dhl',''),
  ('DHL','dhl group','parent','deutsche post dhl',''),
  ('Bosch','robert bosch','parent','robert bosch',''),
  ('Bosch','robert bosch gmbh','parent','robert bosch',''),
  ('Bosch','robert bosch group','parent','robert bosch',''),
  ('Bosch','bosch (robert bosch gmbh)','parent','robert bosch',''),
  ('Siemens','siemens ag','parent','siemens',''),
  ('Siemens','siemens healthineers','subsidiary','siemens healthineers',''),
  ('Siemens','siemens healthineers ag','alias','siemens healthineers',''),
  ('Siemens','siemens energy','subsidiary','siemens energy',''),
  ('Siemens','siemens mobility','subsidiary','siemens mobility',''),
  ('Samsung','samsung electronics','subsidiary','samsung electronics',''),
  ('Samsung','samsung electronics america','alias','samsung electronics',''),
  ('Samsung','samsung electronics (electronics)','alias','samsung electronics',''),
  ('Samsung','samsung biologics','subsidiary','samsung biologics',''),
  ('Samsung','samsung sdi','subsidiary','samsung sdi',''),
  ('Samsung','samsung sdi america','alias','samsung sdi',''),
  ('Samsung','samsung semiconductor','subsidiary','samsung semiconductor',''),
  ('Samsung','samsung semiconductors','subsidiary','samsung semiconductor',''),
  ('Toyota','toyota motor','parent','toyota',''),
  ('Toyota','toyota motor corporation','parent','toyota',''),
  ('BNP Paribas','bnp paribas group','parent','bnp paribas',''),
  ('Yum! Brands','yum! brands inc','parent','yum! brands',''),
  ('Yum! Brands','yum! brands inc.','parent','yum! brands',''),
  ('Yum! Brands','yum! restaurant holdings','parent','yum! brands',''),
  ('IBM','ibm research','subsidiary','ibm research',''),
  ('IBM','ibm security','subsidiary','ibm security',''),
  ('IBM','ibm security (cybersecurity)','alias','ibm security',''),
  ('IBM','ibm cloud','subsidiary','ibm cloud',''),
  ('IBM','ibm consulting','subsidiary','ibm consulting',''),
  ('IBM','ibm watson','subsidiary','ibm watson',''),
  ('IBM','ibm watson talent','alias','ibm watson',''),
  ('Lufthansa','deutsche lufthansa ag','parent','lufthansa',''),
  ('Lufthansa','lufthansa group','parent','lufthansa',''),
  ('Lufthansa','lufthansa cargo','subsidiary','lufthansa cargo',''),
  ('Lufthansa','lufthansa cargo (airline)','subsidiary','lufthansa cargo',''),
  ('Lufthansa','lufthansa technik','subsidiary','lufthansa technik',''),
  ('Lufthansa','lufthansa technik logistik services','alias','lufthansa technik',''),
  ('Lufthansa','lufthansa systems','subsidiary','lufthansa systems',''),
  ('Lufthansa','lufthansa systems (airline)','subsidiary','lufthansa systems',''),
  ('Lufthansa','lufthansa city airline','subsidiary','lufthansa city airlines',''),
  ('Lufthansa','lufthansa city airlines','subsidiary','lufthansa city airlines',''),
  ('Lufthansa','lufthansa cityline','subsidiary','lufthansa cityline',''),
  ('Mondelez','mondelez international','parent','mondelez',''),
  ('Mondelez','mondelez international inc','parent','mondelez',''),
  ('Stellantis','groupe stellantis','parent','stellantis',''),
  ('Telefónica','telefónica group','parent','telefonica',''),
  ('Telefónica','o2 telefonica','subsidiary','o2',''),
  ('Telefónica','o2 telefónica','subsidiary','o2',''),
  ('Vodafone','vodafone idea','subsidiary','vodafone idea',''),
  ('Vodafone','vodafone idea limited','subsidiary','vodafone idea',''),
  ('Vodafone','vodafone idea (vi)','subsidiary','vodafone idea',''),
  ('Vodafone','vodafone idea foundation','alias','vodafone idea',''),
  ('Vodafone','vodafone group','parent','vodafone',''),
  ('Vodafone','vodafone group plc','parent','vodafone',''),
  ('Accenture','accenture plc','parent','accenture',''),
  ('Volvo','volvo ab','parent','volvo',''),
  ('JPMorgan Chase','jpmorgan chase & co.','parent','jpmorgan chase',''),
  ('JPMorgan Chase','jpmorgan chase & co','parent','jpmorgan chase',''),
  ('LVMH','lvmh moët hennessy louis vuitton','parent','lvmh',''),
  ('Novartis','novartis ag','parent','novartis',''),
  ('Honda','honda motor','parent','honda',''),
  ('Honda','honda motor company','parent','honda',''),
  ('Honda','honda motor co., ltd.','parent','honda',''),
  ('Hilton','hilton worldwide holdings','parent','hilton',''),
  ('Hilton','hilton worldwide holdings inc.','parent','hilton',''),
  ('Hilton','hilton hotels & resorts','subsidiary','hilton hotels',''),
  ('Hilton','hilton hotels','subsidiary','hilton hotels',''),
  ('Hilton','hilton curio collection','subsidiary','curio collection',''),
  ('Hilton','hilton grand vacations','subsidiary','hilton grand vacations',''),
  ('TUI','tui ag','parent','tui',''),
  ('TUI','tui group','parent','tui',''),
  ('TUI','tui fly','subsidiary','tui fly',''),
  ('TUI','tui fly deutschland','geo','tui fly',''),
  ('TUI','tui airways','subsidiary','tui airways',''),
  ('BMW','bmw ag','parent','bmw',''),
  ('BMW','bmw group','parent','bmw',''),
  ('BMW','bmw brilliance','subsidiary','bmw brilliance',''),
  ('BMW','bmw brilliance automotive','subsidiary','bmw brilliance',''),
  ('Bayer','bayer ag','parent','bayer',''),
  ('SAP','sap se','parent','sap','');

UPDATE public.company_canonical_names c
SET variant_type = cls.new_variant_type, brand_key = cls.brand_key
FROM _classifications cls
WHERE c.canonical_name = cls.canonical_name AND c.variant_name = cls.variant_name;

CREATE TEMP TABLE _detachments (canonical_name text NOT NULL, variant_name text NOT NULL, reason text) ON COMMIT DROP;
INSERT INTO _detachments VALUES ('Ford','ford foundation','Ford Foundation is independent of Ford Motor');
UPDATE public.company_canonical_names c
SET canonical_name = c.variant_name, variant_type = 'alias', brand_key = lower(public.unaccent(c.variant_name))
FROM _detachments d
WHERE c.canonical_name = d.canonical_name AND c.variant_name = d.variant_name;

CREATE TEMP TABLE _reparents (old_canonical text NOT NULL, new_canonical text NOT NULL, variant_name text NOT NULL, new_variant_type text NOT NULL, brand_key text NOT NULL, reason text) ON COMMIT DROP;
INSERT INTO _reparents VALUES
  ('KFC','Yum! Brands','kfc','subsidiary','kfc',''),
  ('KFC','Yum! Brands','kfc (quick service restaurants)','alias','kfc',''),
  ('KFC','Yum! Brands','kfc uki','alias','kfc',''),
  ('KFC','Yum! Brands','kfc brasil','geo','kfc',''),
  ('KFC','Yum! Brands','kfc brazil','geo','kfc',''),
  ('KFC','Yum! Brands','kfc deutschland','geo','kfc',''),
  ('KFC','Yum! Brands','kfc france','geo','kfc',''),
  ('KFC','Yum! Brands','kfc germany','geo','kfc',''),
  ('KFC','Yum! Brands','kfc germany (yum! brands)','geo','kfc',''),
  ('KFC','Yum! Brands','kfc india','geo','kfc',''),
  ('KFC','Yum! Brands','kfc uk','geo','kfc',''),
  ('Pizza Hut','Yum! Brands','pizza hut','subsidiary','pizza hut',''),
  ('Pizza Hut','Yum! Brands','pizza hut india','geo','pizza hut',''),
  ('Taco Bell','Yum! Brands','taco bell','subsidiary','taco bell',''),
  ('Taco Bell','Yum! Brands','taco bell uk','geo','taco bell',''),
  ('Whatsapp','Meta','whatsapp','subsidiary','whatsapp','');
UPDATE public.company_canonical_names c
SET canonical_name = r.new_canonical, variant_type = r.new_variant_type, brand_key = r.brand_key
FROM _reparents r
WHERE c.canonical_name = r.old_canonical AND c.variant_name = r.variant_name;

UPDATE public.company_canonical_names
SET variant_type = 'geo'
WHERE variant_type = 'alias'
  AND lower(variant_name) <> lower(canonical_name)
  AND variant_name ~* '\m(uk|gb|usa|u\.s\.|u\.s\.a\.|north america|south america|latin america|emea|apac|india|china|brazil|brasil|germany|deutschland|france|spain|italy|japan|korea|mexico|canada|australia|argentina|chile|colombia|peru|netherlands|sweden|norway|denmark|finland|switzerland|austria|poland|turkey|saudi arabia|uae|singapore|vietnam|thailand|indonesia|philippines|malaysia|hong kong|taiwan|new zealand|south africa|nigeria|kenya|egypt|israel|ireland|portugal|belgium|hungary|czech republic|czechia|romania|greece|russia|do brasil|of north america|of america)\M'
  AND variant_name !~* '\mus bank\M';

UPDATE public.company_canonical_names SET brand_key = lower(public.unaccent(canonical_name)) WHERE brand_key IS NULL OR brand_key = '';
ALTER TABLE public.company_canonical_names ALTER COLUMN brand_key SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ccn_brand_key ON public.company_canonical_names (brand_key);
CREATE INDEX IF NOT EXISTS idx_ccn_canonical_brand_key ON public.company_canonical_names (lower(canonical_name), brand_key);

CREATE OR REPLACE FUNCTION public.get_company_subsidiaries(p_canonical text)
RETURNS TABLE(subsidiary text, variant_type text, mention_count integer)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $function$
  WITH subs AS (
    SELECT s.brand_key, s.variant_name, s.variant_type, length(s.variant_name) AS vlen
    FROM public.company_canonical_names s
    WHERE lower(s.canonical_name) = lower(p_canonical)
      AND s.variant_type = 'subsidiary'
      AND lower(s.variant_name) <> lower(s.canonical_name)
  ),
  pick AS (
    SELECT DISTINCT ON (brand_key) brand_key, variant_name, variant_type
    FROM subs
    ORDER BY brand_key, vlen, variant_name
  )
  SELECT p.variant_name AS subsidiary, p.variant_type, COALESCE(m.cnt, 0)::int AS mention_count
  FROM pick p
  LEFT JOIN LATERAL (
    SELECT count(*) AS cnt FROM public.prompt_responses pr
    WHERE pr.for_index = true AND EXISTS (
      SELECT 1 FROM public.company_canonical_names sib
      WHERE sib.brand_key = p.brand_key AND lower(sib.canonical_name) = lower(p_canonical)
        AND pr.detected_competitors ILIKE '%' || sib.variant_name || '%'
    )
  ) m ON true
  ORDER BY mention_count DESC, p.variant_name;
$function$;

COMMIT;
