-- Recovered verbatim from supabase_migrations.schema_migrations.
-- Applied to production as migration version 20260205160000; this file was
-- back-filled afterwards and therefore post-dates the deployment.

-- Create table for known sources
CREATE TABLE IF NOT EXISTS public.known_sources (
  name text PRIMARY KEY
)
-- Enable RLS (though public read is fine)
ALTER TABLE public.known_sources ENABLE ROW LEVEL SECURITY
GRANT SELECT ON public.known_sources TO anon, authenticated, service_role
-- Insert known sources
INSERT INTO public.known_sources (name) VALUES
('5w public relations'),
('5wpr'),
('4cv3 financial services'),
('4cv3 financial'),
('4cv3'),
('3cloud'),
('3 cloud'),
('3search'),
('3 search'),
('air force association'),
('airforceassociation'),
('afa'),
('american transmission co.'),
('american transmission co'),
('american transmission company'),
('american transmission'),
('american trucking association'),
('americantruckingassociation'),
('ata'),
('american trucking association logo'),
('b corporation'),
('b corp'),
('bcorp'),
('b-corp'),
('beach house pr'),
('beachhousepr'),
('beach house public relations'),
('beachhouse public relations'),
('big 4'),
('big4'),
('big four'),
('bigfour'),
('black professionals in tech network'),
('blackprofessionalsintechnetwork'),
('black in gaming'),
('blackingaming'),
('black girls code'),
('blackgirlscode'),
('bgc'),
('biz4group'),
('biz 4 group'),
('biz2credit'),
('biz 2 credit'),
('a good day in va'),
('a good day in va (agdva)'),
('agdva'),
('a good day in virginia'),
('andreessen horowitz'),
('a16z'),
('universum'),
('glassdoor'),
('indeed'),
('linkedin'),
('monster'),
('ziprecruiter'),
('careerbuilder'),
('simplyhired'),
('snagajob'),
('jobvite'),
('greenhouse'),
('lever'),
('bamboohr'),
('jobstreet'),
('seek'),
('science careers'),
('sciencecareers'),
('scientist.com'),
('scientistcom'),
('scientific search'),
('scientificsearch'),
('smartrecruiters'),
('smart recruiters'),
('starred'),
('storm2'),
('storm3'),
('sustainably yours'),
('sustainablyyours'),
('sustainability magazine'),
('sustainabilitymagazine'),
('surf search'),
('surfsearch'),
('symphony talent'),
('symphonytalent'),
('talent board'),
('talentboard'),
('talent hero media'),
('talentheromedia'),
('talent partners'),
('talentpartners'),
('talentfoot'),
('talentful'),
('talentlyft'),
('teamtailor'),
('team tailor'),
('techrepublic'),
('tech republic'),
('technorely'),
('the executive search group'),
('theexecutivesearchgroup'),
('executive search group'),
('executivesearchgroup'),
('the philadelphia inquirer'),
('thephiladelphiainquirer'),
('philadelphia inquirer'),
('philadelphiainquirer'),
('the people brand'),
('thepeoplebrand'),
('people brand'),
('peoplebrand'),
('the reinvestment fund'),
('thereinvestmentfund'),
('reinvestment fund'),
('reinvestmentfund'),
('the software report'),
('thesoftwarereport'),
('software report'),
('softwarereport'),
('top workplaces'),
('topworkplaces'),
('top brands'),
('topbrands'),
('zoominfo'),
('zoom info'),
('trustcruit'),
('trust cruit'),
('web3.career'),
('web3career'),
('web3 career'),
('what if!'),
('what if'),
('whatif'),
('workable'),
('workato'),
('workbright'),
('work bright'),
('workhuman'),
('work human'),
('workiva'),
('work iva'),
('workleap'),
('work leap'),
('worktango'),
('work tango'),
('world economic forum'),
('worldeconomicforum'),
('worldsafe1st inc.'),
('worldsafe1st inc'),
('worldsafe1st'),
('world safe 1st'),
('world wide technology'),
('worldwidetechnology'),
('wwt'),
('wwf'),
('world wildlife fund'),
('worldwildlifefund'),
('reed'),
('resume.io'),
('resumeio'),
('totaljobs'),
('cv-library'),
('jobsdb'),
('naukri'),
('timesjobs'),
('shine'),
('stepstone'),
('xing'),
('pnet'),
('phenom'),
('pinnacle'),
('jobrapido'),
('adzuna'),
('jobsora'),
('jooble'),
('trovit'),
('jobisjob'),
('joblift'),
('jobted'),
('jobleads'),
('jobcase'),
('flexjobs'),
('the muse'),
('vault'),
('fairygodboss'),
('great places to work'),
('great place to work'),
('great place to work®'),
('great places to work®'),
('fortune''s best companies to work for'),
('fortune best companies to work for'),
('best companies to work for'),
('best companies'),
('fortune 100'),
('fortune 500'),
('fortune 1000'),
('accur'),
('accur recruiting services'),
('achievers'),
('cpg connect'),
('cpg connect recruitment'),
('cpg connect recruiting'),
('cryptocurrencyjobs.co'),
('cryptocurrencyjobs'),
('cryptorecruit'),
('culturecon'),
('faang'),
('faa'),
('federal aviation administration'),
('federalaviationadministration'),
('fahrenheit 212'),
('fahrenheit212'),
('fair360'),
('fair 360'),
('f6s'),
('f6 s'),
('ismartrecruit'),
('i smart recruit'),
('lemonade crypto climate coalition'),
('lemonade crypto climate'),
('levels.fyi'),
('levels fyi'),
('levelsfyi'),
('lifedojo'),
('life dojo'),
('make-a-wish'),
('make a wish'),
('makeawish'),
('built in'),
('dice'),
('dice.com'),
('hired'),
('hired.com'),
('triplebyte'),
('triplebyte.com'),
('hackerrank'),
('leetcode'),
('codewars'),
('topcoder'),
('coderbyte'),
('interviewbit'),
('pramp'),
('interviewing.io'),
('interviewingio'),
('interview cake'),
('interviewcake'),
('pramp.com'),
('mock interview'),
('practice coding'),
('coding interview'),
('tech jobs'),
('techjobs'),
('remote jobs'),
('remotejobs'),
('weworkremotely'),
('we work remotely'),
('remote.co'),
('remoteco'),
('remoteok'),
('remote ok'),
('remotely'),
('justremote'),
('just remote'),
('jobspresso'),
('jobs presso'),
('skip the drive'),
('skipthedrive'),
('working nomads'),
('workingnomads'),
('pangian'),
('remote work'),
('remotework'),
('robert half'),
('roberthalf'),
('kelly services'),
('kellyservices'),
('randstad'),
('adecco'),
('manpower'),
('allegis group'),
('allegis'),
('aerotek'),
('teksystems'),
('kforce'),
('k force'),
('insight global'),
('insightglobal'),
('actalent'),
('a talent'),
('volt'),
('volttemp'),
('volt temp'),
('talentburst'),
('talent burst'),
('modis'),
('harvey nash'),
('harveynash'),
('hays'),
('michael page'),
('michaelpage'),
('page group'),
('pagegroup'),
('hudson'),
('hudson global'),
('hudsonglobal'),
('spencer stuart'),
('spencerstuart'),
('egon zehnder'),
('egonzehnder'),
('korn ferry'),
('kornferry'),
('heidrick & struggles'),
('heidrick struggles'),
('heidrickandstruggles'),
('russell reynolds'),
('russellreynolds'),
('boyden'),
('odgers berndtson'),
('odgersberndtson'),
('angel list'),
('angellist'),
('wellfound'),
('crunchbase'),
('bloomberg'),
('reuters'),
('forbes'),
('fortune'),
('entrepreneur'),
('entrepreneur magazine'),
('business insider'),
('cnbc'),
('wsj'),
('wall street journal'),
('financial times'),
('the economist'),
('harvard business review'),
('mckinsey quarterly'),
('hbr'),
('techcrunch'),
('venturebeat'),
('the information'),
('the verge'),
('wired'),
('ars technica'),
('engadget'),
('gizmodo'),
('reddit'),
('quora'),
('stack overflow'),
('stackoverflow'),
('github'),
('gitlab'),
('medium'),
('substack'),
('linkedin learning'),
('coursera'),
('udemy'),
('edx'),
('khan academy'),
('youtube'),
('vimeo'),
('ted'),
('tedx'),
('wikipedia'),
('wikimedia'),
('imdb'),
('rottentomatoes'),
('metacritic'),
('pitchfork'),
('rolling stone'),
('variety'),
('hollywood reporter'),
('deadline'),
('entertainment weekly'),
('people'),
('us weekly'),
('tmz'),
('buzzfeed'),
('vice'),
('vox'),
('vox media'),
('the atlantic'),
('new yorker'),
('new york times'),
('washington post'),
('los angeles times'),
('usa today'),
('cnn'),
('fox news'),
('msnbc'),
('abc news'),
('cbs news'),
('nbc news'),
('bbc'),
('bbc news'),
('the guardian'),
('independent'),
('daily mail'),
('the sun'),
('mirror'),
('telegraph'),
('daily express'),
('sky news'),
('itv'),
('channel 4'),
('al jazeera'),
('associated press'),
('ap news'),
('agence france-presse'),
('afp'),
('bloomberg news'),
('axios'),
('politico'),
('the hill'),
('roll call'),
('c-span'),
('npr'),
('pbs'),
('propublica'),
('the intercept'),
('mother jones'),
('the nation'),
('jacobin'),
('democracy now'),
('the young turks'),
('tyt'),
('breaking points'),
('rising'),
('the david pakman show'),
('securing america'),
('the ben shapiro show'),
('the daily wire'),
('prageru'),
('prager u'),
('the blaze'),
('infowars'),
('oann'),
('newsmax'),
('one america news'),
('real clear politics'),
('538'),
('fivethirtyeight'),
('the fivethirtyeight'),
('realclearpolitics'),
('the cook political report'),
('inside elections'),
('sabato''s crystal ball'),
('larry sabato'),
('the rothenberg political report')
ON CONFLICT (name) DO NOTHING
-- Create View for Scored Rankings
-- 1. Calculate Industry Totals (Denominator)
-- 2. Calculate Company Scores (Numerator)
-- 3. Filter out known sources and broad-industry companies

CREATE OR REPLACE VIEW public.mv_rankings_scored AS
WITH industry_totals AS (
  SELECT 
    industry, 
    country, 
    count(*) as total_combinations 
  FROM public.mv_industry_stats 
  GROUP BY industry, country
),
company_stats AS (
  SELECT 
    m.company_name,
    count(DISTINCT m.industry) as industry_count
  FROM public.mv_company_mentions m
  GROUP BY m.company_name
),
total_industries AS (
  SELECT count(DISTINCT industry) as total_count FROM public.mv_industry_stats
),
company_scores AS (
  SELECT 
    m.industry, 
    m.country, 
    m.company_name, 
    count(DISTINCT m.ai_model || '::' || m.theme) as company_combinations
  FROM public.mv_company_mentions m
  GROUP BY m.industry, m.country, m.company_name
)
SELECT 
  c.company_name,
  c.industry,
  c.country,
  c.company_combinations,
  t.total_combinations,
  -- Calculate Score: (Numerator / Denominator) * 100
  ROUND((c.company_combinations::numeric / NULLIF(t.total_combinations, 0)::numeric) * 100, 2) as visibility_score
FROM company_scores c
JOIN industry_totals t ON c.industry = t.industry AND c.country = t.country
LEFT JOIN public.known_sources ks ON lower(trim(c.company_name)) = ks.name
LEFT JOIN company_stats cs ON c.company_name = cs.company_name
CROSS JOIN total_industries ti
WHERE 
  ks.name IS NULL -- Exclude known sources
  AND (cs.industry_count::float / NULLIF(ti.total_count, 0)::float) <= 0.5 -- Exclude companies present in >50% industries
  -- Also exclude based on regex patterns (simplified version of sourceFiltering.ts)
  AND c.company_name !~* '^(recruiting|staffing|job board|career site)'
GRANT SELECT ON public.mv_rankings_scored TO anon, authenticated, service_role
