-- Recovered verbatim from supabase_migrations.schema_migrations.
-- Applied to production as migration version 20260809070631; this file was
-- back-filled afterwards and therefore post-dates the deployment.

-- UAE canonical-name cleanup (August 2026 index). Mirrors repo migration
-- 20260809130000_uae_canonical_cleanup.sql — see that file for full rationale.
-- 1. Geo variants of existing canonicals; 2. Emirates-family folds;
-- 3. Standalone UAE employers (canonical casing + groupings + domains, NO tiers).

INSERT INTO public.company_canonical_names
  (variant_name, canonical_name, variant_type, brand_key, source, is_verified)
SELECT v.variant_name, v.canonical_name, 'geo',
       lower(public.unaccent(v.canonical_name)), 'manual', true
FROM (VALUES
  ('microsoft uae',                        'Microsoft'),
  ('microsoft gulf',                       'Microsoft'),
  ('google uae',                           'Google'),
  ('google middle east',                   'Google'),
  ('google cloud uae',                     'Google'),
  ('google cloud dubai',                   'Google'),
  ('amazon uae',                           'Amazon'),
  ('amazon gulf',                          'Amazon'),
  ('amazon middle east',                   'Amazon'),
  ('amazon web services uae',              'Amazon'),
  ('amazon web services (aws) uae',        'Amazon'),
  ('aws uae',                              'Amazon'),
  ('ibm uae',                              'IBM'),
  ('ibm middle east',                      'IBM'),
  ('hsbc uae',                             'HSBC'),
  ('hsbc middle east',                     'HSBC'),
  ('hsbc bank middle east',                'HSBC'),
  ('cleveland clinic abu dhabi',           'Cleveland Clinic'),
  ('l''oréal middle east',                 'L''Oréal'),
  ('l''oréal uae',                         'L''Oréal'),
  ('ubisoft abu dhabi',                    'Ubisoft'),
  ('ubisoft dubai',                        'Ubisoft'),
  ('standard chartered uae',               'Standard Chartered'),
  ('standard chartered bank uae',          'Standard Chartered Bank'),
  ('huawei uae',                           'Huawei'),
  ('huawei middle east',                   'Huawei'),
  ('zurich insurance middle east',         'Zurich'),
  ('zurich middle east',                   'Zurich'),
  ('carrefour uae',                        'Carrefour'),
  ('nestlé middle east',                   'Nestlé'),
  ('nestlé mena',                          'Nestlé'),
  ('oracle uae',                           'Oracle'),
  ('oracle middle east',                   'Oracle'),
  ('metlife uae',                          'Metlife'),
  ('metlife gulf',                         'Metlife'),
  ('siemens uae',                          'Siemens'),
  ('siemens middle east',                  'Siemens'),
  ('unilever gulf',                        'Unilever'),
  ('unilever mena',                        'Unilever'),
  ('unilever uae',                         'Unilever'),
  ('unilever middle east',                 'Unilever'),
  ('h&m uae',                              'H & M'),
  ('sap uae',                              'SAP'),
  ('sap mena',                             'SAP'),
  ('ikea uae',                             'IKEA'),
  ('citibank uae',                         'Citibank'),
  ('citi uae',                             'Citi'),
  ('citigroup uae',                        'Citigroup'),
  ('barclays uae',                         'Barclays'),
  ('cisco uae',                            'Cisco'),
  ('shiseido middle east',                 'Shiseido'),
  ('roche uae',                            'Roche'),
  ('roche middle east',                    'Roche'),
  ('roche diagnostics middle east',        'Roche'),
  ('dhl uae',                              'DHL'),
  ('dhl express uae',                      'DHL'),
  ('dhl global forwarding uae',            'DHL'),
  ('schneider electric uae',               'Schneider Electric'),
  ('marks & spencer uae',                  'Marks & Spencer'),
  ('sephora uae',                          'Sephora'),
  ('sephora middle east',                  'Sephora'),
  ('pepsico uae',                          'PepsiCo'),
  ('pepsico middle east',                  'PepsiCo'),
  ('pepsico mena',                         'PepsiCo'),
  ('db schenker uae',                      'Db Schenker'),
  ('abb uae',                              'Abb'),
  ('adidas uae',                           'Adidas'),
  ('kuehne + nagel uae',                   'Kuehne + Nagel'),
  ('kuehne+nagel uae',                     'Kuehne+Nagel'),
  ('thales uae',                           'Thales'),
  ('biocon biologics mena',                'Biocon'),
  ('generali uae',                         'Generali'),
  ('airbus middle east',                   'Airbus'),
  ('ericsson uae',                         'Ericsson'),
  ('henkel uae',                           'Henkel'),
  ('lg electronics uae',                   'LG Electronics'),
  ('zara uae',                             'Zara'),
  ('nike uae',                             'Nike'),
  ('nike middle east',                     'Nike'),
  ('salesforce uae',                       'Salesforce'),
  ('allianz uae',                          'Allianz'),
  ('allianz middle east',                  'Allianz'),
  ('maersk uae',                           'Maersk'),
  ('maersk dubai',                         'Maersk'),
  ('novartis middle east',                 'Novartis'),
  ('novartis uae',                         'Novartis'),
  ('accenture middle east',                'Accenture'),
  ('accenture uae',                        'Accenture'),
  ('pfizer uae',                           'Pfizer'),
  ('pfizer gulf',                          'Pfizer'),
  ('coca-cola middle east',                'Coca-Cola'),
  ('coca-cola uae',                        'Coca-Cola'),
  ('stryker uae',                          'Stryker'),
  ('pwc uae',                              'PwC'),
  ('pwc middle east',                      'PwC'),
  ('estée lauder companies middle east',   'Estée Lauder'),
  ('the estée lauder companies middle east', 'The Estée Lauder Companies'),
  ('novo nordisk uae',                     'Novo Nordisk'),
  ('kpmg uae',                             'KPMG'),
  ('fedex uae',                            'FedEx'),
  ('fedex express uae',                    'Fedex Express'),
  ('astrazeneca gulf',                     'AstraZeneca'),
  ('dell technologies uae',                'Dell'),
  ('honeywell middle east',                'Honeywell'),
  ('honeywell uae',                        'Honeywell'),
  ('pizzaexpress uae',                     'Pizzaexpress'),
  ('aig uae',                              'AIG'),
  ('aig middle east',                      'AIG'),
  ('sun life uae',                         'Sun Life'),
  ('bosch middle east',                    'Bosch'),
  ('ubs uae',                              'UBS'),
  ('uniqlo uae',                           'Uniqlo'),
  ('forbes middle east',                   'Forbes'),
  ('nokia uae',                            'Nokia'),
  ('nokia dubai',                          'Nokia'),
  ('nokia abu dhabi',                      'Nokia'),
  ('adecco middle east',                   'Adecco'),
  ('adecco uae',                           'Adecco'),
  ('basf uae',                             'Basf'),
  ('illumina middle east',                 'Illumina'),
  ('kempinski hotels uae',                 'Kempinski Hotels'),
  ('gameloft abu dhabi',                   'Gameloft'),
  ('gameloft dubai',                       'Gameloft'),
  ('procter & gamble middle east',         'Procter & Gamble'),
  ('procter & gamble mena',                'Procter & Gamble'),
  ('p&g middle east',                      'P & G'),
  ('boeing middle east',                   'Boeing'),
  ('ey mena',                              'EY'),
  ('ey uae',                               'EY'),
  ('rtx uae',                              'RTX'),
  ('galeries lafayette dubai',             'Galeries Lafayette'),
  ('atlassian uae',                        'Atlassian'),
  ('ceva logistics uae',                   'Ceva Logistics'),
  ('uber middle east',                     'Uber'),
  ('gap middle east',                      'Gap'),
  ('apple middle east',                    'Apple'),
  ('wizz air abu dhabi',                   'Wizz Air'),
  ('mars gcc',                             'Mars'),
  ('mars middle east',                     'Mars'),
  ('marriott international uae',           'Marriott'),
  ('rolls-royce middle east',              'Rolls-Royce'),
  ('stada uae',                            'Stada'),
  ('lush middle east',                     'Lush'),
  ('tommy hilfiger uae',                   'Tommy Hilfiger'),
  ('lancôme uae',                          'Lancôme'),
  ('the walt disney company mena',         'Disney'),
  ('premier inn middle east',              'Premier Inn'),
  ('nykaa middle east',                    'Nykaa'),
  ('bloomingdale''s middle east',          'Bloomingdale''s'),
  ('hilton uae',                           'Hilton'),
  ('levi''s uae',                          'Levi''s'),
  ('hp inc. uae',                          'HP'),
  ('ferrero uae',                          'Ferrero'),
  ('samsung electronics uae',              'Samsung'),
  ('samsung gulf',                         'Samsung'),
  ('samsung gulf electronics uae',         'Samsung'),
  ('meta (facebook) uae',                  'Meta'),
  ('four seasons dubai',                   'Four Seasons'),
  ('four seasons hotels dubai',            'Four Seasons'),
  ('four seasons hotels uae',              'Four Seasons'),
  ('taj dubai',                            'Taj'),
  ('johnson & johnson middle east',        'Johnson & Johnson'),
  ('grant thornton uae',                   'Grant Thornton'),
  ('servicenow uae',                       'ServiceNow'),
  ('hellmann worldwide logistics uae',     'Hellmann Worldwide Logistics'),
  ('saab middle east',                     'Saab'),
  ('workday uae',                          'Workday'),
  ('coty middle east',                     'Coty'),
  ('veolia middle east',                   'Veolia'),
  ('great place to work uae',              'Great Place to Work'),
  ('dow uae',                              'Dow'),
  ('gsk middle east',                      'GSK'),
  ('bdo uae',                              'BDO'),
  ('abbott laboratories gulf',             'Abbott'),
  ('atlas copco uae',                      'Atlas Copco'),
  ('ups uae',                              'UPS'),
  ('toms middle east',                     'Toms'),
  ('sanofi gulf',                          'Sanofi'),
  ('canon middle east',                    'Canon'),
  ('bayer middle east',                    'Bayer'),
  ('prudential middle east',               'Prudential'),
  ('sodexo middle east',                   'Sodexo'),
  ('amgen uae',                            'Amgen'),
  ('philips uae',                          'Philips'),
  ('aster dm healthcare gcc',              'Aster Dm Healthcare'),
  ('decathlon uae',                        'Decathlon'),
  ('indeed uae',                           'Indeed'),
  ('entrepreneur middle east',             'Entrepreneur'),
  ('collins aerospace uae',                'Collins Aerospace'),
  ('fortinet uae',                         'Fortinet'),
  ('gac uae',                              'Gac'),
  ('epson uae',                            'Epson')
) AS v(variant_name, canonical_name)
ON CONFLICT (variant_name) DO NOTHING;

INSERT INTO public.company_canonical_names
  (variant_name, canonical_name, variant_type, brand_key, source, is_verified)
VALUES
  ('emirates airline',    'Emirates', 'alias',      'emirates', 'manual', true),
  ('emirates group',      'Emirates', 'alias',      'emirates', 'manual', true),
  ('the emirates group',  'Emirates', 'alias',      'emirates', 'manual', true),
  ('emirates skycargo',   'Emirates', 'subsidiary', 'emirates', 'manual', true)
ON CONFLICT (variant_name) DO NOTHING;

INSERT INTO public.company_canonical_names
  (variant_name, canonical_name, variant_type, brand_key, website_domain, source, is_verified)
SELECT v.variant_name, v.canonical_name, v.variant_type,
       lower(public.unaccent(v.canonical_name)), v.website_domain, 'manual', true
FROM (VALUES
  ('emirates nbd',                          'Emirates NBD',               'alias', 'emiratesnbd.com'),
  ('etihad airways',                        'Etihad Airways',             'alias', 'etihad.com'),
  ('first abu dhabi bank',                  'First Abu Dhabi Bank',       'alias', 'bankfab.com'),
  ('etisalat',                              'Etisalat',                   'alias', 'etisalat.ae'),
  ('du',                                    'du',                         'alias', 'du.ae'),
  ('adnoc',                                 'ADNOC',                      'alias', 'adnoc.ae'),
  ('adcb',                                  'ADCB',                       'alias', 'adcb.com'),
  ('seha',                                  'SEHA',                       'alias', 'seha.ae'),
  ('adnic',                                 'ADNIC',                      'alias', 'adnic.ae'),
  ('mubadala',                              'Mubadala',                   'alias', 'mubadala.com'),
  ('emirates global aluminium',             'Emirates Global Aluminium',  'alias', 'ega.ae'),
  ('noon',                                  'noon',                       'alias', 'noon.com'),
  ('lulu group',                            'Lulu Group',                 'alias', 'lulugroupinternational.com'),
  ('mashreq',                               'Mashreq',                    'alias', 'mashreq.com'),
  ('majid al futtaim',                      'Majid Al Futtaim',           'alias', 'majidalfuttaim.com'),
  ('chalhoub group',                        'Chalhoub Group',             'alias', 'chalhoubgroup.com'),
  ('jumeirah group',                        'Jumeirah Group',             'alias', 'jumeirah.com'),
  ('careem',                                'Careem',                     'alias', 'careem.com'),
  ('g42',                                   'G42',                        'alias', 'g42.ai'),
  ('flydubai',                              'flydubai',                   'alias', 'flydubai.com'),
  ('air arabia',                            'Air Arabia',                 'alias', 'airarabia.com'),
  ('julphar',                               'Julphar',                    'alias', 'julphar.net'),
  ('masdar',                                'Masdar',                     'alias', 'masdar.ae'),
  ('purehealth',                            'PureHealth',                 'alias', 'purehealth.ae'),
  ('burjeel holdings',                      'Burjeel Holdings',           'alias', 'burjeelholdings.com'),
  ('mbc group',                             'MBC Group',                  'alias', 'mbc.net'),
  ('al tayer group',                        'Al Tayer Group',             'alias', 'altayer.com'),
  ('al-futtaim',                            'Al-Futtaim',                 'alias', 'alfuttaim.com'),
  ('dubai islamic bank',                    'Dubai Islamic Bank',         'alias', 'dib.ae'),
  ('commercial bank of dubai',              'Commercial Bank of Dubai',   'alias', 'cbd.ae'),
  ('dubai airports',                        'Dubai Airports',             'alias', 'dubaiairports.ae'),
  ('nmc healthcare',                        'NMC Healthcare',             'alias', 'nmc.ae'),
  ('emaar',                                 'Emaar',                      'alias', 'emaar.com'),
  ('abu dhabi national oil company',        'ADNOC',                      'alias', NULL),
  ('abu dhabi commercial bank',             'ADCB',                       'alias', NULL),
  ('abu dhabi health services company',     'SEHA',                       'alias', NULL),
  ('abu dhabi national insurance company',  'ADNIC',                      'alias', NULL),
  ('mubadala investment company',           'Mubadala',                   'alias', NULL),
  ('ega',                                   'Emirates Global Aluminium',  'alias', NULL),
  ('noon.com',                              'noon',                       'alias', NULL),
  ('lulu hypermarket',                      'Lulu Group',                 'alias', NULL),
  ('mashreq bank',                          'Mashreq',                    'alias', NULL),
  ('national bank of abu dhabi',            'First Abu Dhabi Bank',       'alias', NULL),
  ('etisalat/e& uae',                       'Etisalat',                   'alias', NULL),
  ('e&',                                    'Etisalat',                   'alias', NULL),
  ('emirates integrated telecommunications company', 'du',                'alias', NULL),
  ('gulf pharmaceutical industries',        'Julphar',                    'alias', NULL),
  ('g42 healthcare',                        'G42',                        'subsidiary', NULL),
  ('emaar hospitality group',               'Emaar',                      'subsidiary', NULL)
) AS v(variant_name, canonical_name, variant_type, website_domain)
ON CONFLICT (variant_name) DO NOTHING;
