-- Recovered verbatim from supabase_migrations.schema_migrations.
-- Applied to production as migration version 20260820111202; this file was
-- back-filled afterwards and therefore post-dates the deployment.

insert into company_canonical_names (variant_name, canonical_name, website_domain, source, variant_type, is_verified, brand_key)
select v.variant_name, v.canonical_name, v.website_domain, 'manual', v.variant_type, true, lower(v.canonical_name)
from (values
 ('al-futtaim group','Al-Futtaim',null,'alias'),
 ('al futtaim group','Al-Futtaim',null,'alias'),
 ('al futtaim','Al-Futtaim',null,'alias'),
 ('al-futtaim groups','Al-Futtaim',null,'alias'),
 ('al-futtaim family of companies','Al-Futtaim',null,'alias'),
 ('al-futtaim electronics','Al-Futtaim',null,'subsidiary'),
 ('al futtaim electronics engineering and technologies','Al-Futtaim',null,'subsidiary'),
 ('al-futtaim logistics','Al-Futtaim',null,'subsidiary'),
 ('al-futtaim travel','Al-Futtaim',null,'subsidiary'),
 ('al-futtaim insurance','Al-Futtaim',null,'subsidiary'),
 ('al futtaim group insurance','Al-Futtaim',null,'subsidiary'),
 ('al futtaim health and insurance','Al-Futtaim',null,'subsidiary'),
 ('al-futtaim ikea','Al-Futtaim',null,'subsidiary'),
 ('al futtaim industrial','Al-Futtaim',null,'subsidiary'),
 ('al-futtaim industrie','Al-Futtaim',null,'subsidiary'),
 ('majid al futtaim retail','Majid Al Futtaim',null,'subsidiary'),
 ('majid al futtaim group','Majid Al Futtaim',null,'alias'),
 ('majid al futtaim holdings','Majid Al Futtaim',null,'alias'),
 ('majid al futtaim entertainment','Majid Al Futtaim',null,'subsidiary'),
 ('majid al futtaim le commerce','Majid Al Futtaim',null,'subsidiary'),
 ('majid al futtaim lifestyle','Majid Al Futtaim',null,'subsidiary'),
 ('majid al futtaim luxury','Majid Al Futtaim',null,'subsidiary'),
 ('majid al futtaim travel','Majid Al Futtaim',null,'subsidiary'),
 ('mubadala aerospace','Mubadala',null,'subsidiary'),
 ('mubadala petroleum','Mubadala',null,'subsidiary'),
 ('mubadala energy','Mubadala',null,'subsidiary'),
 ('mubadala healthcare','Mubadala',null,'subsidiary'),
 ('mubadala technology','Mubadala',null,'subsidiary'),
 ('mubadala aeronautics','Mubadala',null,'subsidiary'),
 ('mubadala bio','Mubadala',null,'subsidiary'),
 ('rotana','Rotana Hotels','rotana.com','alias'),
 ('rotana hotel management corporation','Rotana Hotels',null,'alias'),
 ('rotana hotels & resorts','Rotana Hotels',null,'alias'),
 ('rotana hotels','Rotana Hotels',null,'alias'),
 ('jumeirah','Jumeirah Group','jumeirah.com','alias'),
 ('jumeirah hotels & resorts','Jumeirah Group',null,'alias'),
 ('dnata travel','dnata',null,'subsidiary'),
 ('dnata travels','dnata',null,'subsidiary'),
 ('dnata logistics','dnata',null,'subsidiary'),
 ('lulu group international','Lulu Group','lulugroupinternational.com','alias'),
 ('lulu','Lulu Group',null,'alias'),
 ('du (eitc)','du','du.ae','alias'),
 ('emirates integrated telecommunications company','du',null,'alias'),
 ('eitc','du',null,'alias'),
 ('adia','ADIA','adia.ae','alias'),
 ('abu dhabi investment authority','ADIA',null,'alias'),
 ('masdar clean energy','Masdar','masdar.ae','subsidiary'),
 ('abu dhabi future energy company','Masdar',null,'alias'),
 ('damac group','DAMAC',null,'alias'),
 ('damac hotels & resorts','DAMAC',null,'subsidiary'),
 ('g42 group','G42',null,'alias'),
 ('g42 / group 42','G42',null,'alias'),
 ('nakheel hospitality','Nakheel Properties',null,'subsidiary'),
 ('meraas leisure and entertainment','Meraas',null,'subsidiary'),
 ('emaar entertainment','Emaar',null,'subsidiary'),
 ('adcb hayyak (abu dhabi commercial bank)','ADCB',null,'alias'),
 ('abu dhabi commercial bank','ADCB',null,'alias'),
 ('mashreqbank','Mashreq',null,'alias')
) as v(variant_name, canonical_name, website_domain, variant_type)
where not exists (
 select 1 from company_canonical_names c where lower(c.variant_name)=v.variant_name
);
